[package]
name = "boosh_dsp"
version = "0.1.0"
authors = ["Oliver Stenning <18360865+ostenning@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
